log:
  level: INFO

api:
  insecure: false
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  defaultResolver:
    acme:
      email: "example@example.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "http"
